Add a unit test to illustrate the pyvenv bootstrap issue
This module that manage python needs python to be installed in order to
work properly under certain conditions.

When python is not installed on a node, the python_version fact does not
have a value.  When using `python::pyvenv` on such a system without a
specific version set, a call of the split() function on this unde value
cause an error te be raised:

```
   Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, The function 'split' was called with arguments it does not accept. It expects one of:
    (String str, String pattern)
      rejected: parameter 'str' expects a String value, got Undef
    (String str, Regexp pattern)
      rejected: parameter 'str' expects a String value, got Undef
    (String str, Type[Regexp] pattern)
      rejected: parameter 'str' expects a String value, got Undef
    (Sensitive[String] sensitive, String pattern)
      rejected: parameter 'sensitive' expects a Sensitive[String] value, got Undef
    (Sensitive[String] sensitive, Regexp pattern)
      rejected: parameter 'sensitive' expects a Sensitive[String] value, got Undef
    (Sensitive[String] sensitive, Type[Regexp] pattern)
      rejected: parameter 'sensitive' expects a Sensitive[String] value, got Undef (file: /etc/puppetlabs/code/environments/production/modules/python/manifests/pyvenv.pp, line: 48, column: 34) (file: /etc/puppetlabs/code/environments/production/modules/taiga/manifests/back/install.pp, line: 15) on node debian12-64-puppet7.example.com
```