Use the wheel group by default on FreeBSD
FreeBSD does not have a 'root' group.  System files owned by the 'root'
user belong to the 'wheel' group, so use that group by default.

This allow to use python::pip without the need to explicitly set the
`group` parameter to avoid the error:

> Error: Could not execute posix command: Invalid group: root